name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalar Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Subir containers Docker (etl e outros serviços)
      - name: Build and start Docker containers for ETL
        run: docker compose -f Application/etl/docker-compose.yml up -d --build

      # Instalar dependências do backend em Node.js
      - name: Install dependencies for backend
        working-directory: Application/backend
        run: npm install

      - name: Run tests for backend
        working-directory: Application/backend
        run: npm test

      # Rodar a aplicação em Node.js
      - name: Start Node.js backend
        working-directory: Application/backend
        run: npm start &
          sleep 30
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      # Derrubar containers Docker (etl e outros serviços)
      - name: Stop and remove Docker containers for ETL
        run: docker compose -f Application/etl/docker-compose.yml down